/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Edgar Rios' at '10/03/17 10:30 AM' with Gradle 3.2.1
 *
 * @author Edgar Rios, @date 10/03/17 10:30 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
